package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private String funId;
    private String name;
    private String phone;
    private String headImage;
    private String backImage;

    public User() {
    }

    public User(String funId) {
        this.funId = funId;
    }

    public User(String funId, String name, String phone, String headImage, String backImage) {
        this.funId = funId;
        this.name = name;
        this.phone = phone;
        this.headImage = headImage;
        this.backImage = backImage;
    }

    public String getFunId() {
        return funId;
    }

    public void setFunId(String funId) {
        this.funId = funId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getHeadImage() {
        return headImage;
    }

    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }

    public String getBackImage() {
        return backImage;
    }

    public void setBackImage(String backImage) {
        this.backImage = backImage;
    }

}
