package com.ytying.ytblog.model.domin;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.ytying.ytblog.model.DoObject;

import java.io.Serializable;

/**
 * Entity mapped to table USER.
 */
public class User extends DoObject implements Serializable{

    private String funId;
    private String name;
    private String phone;
    private String headImage;
    private String backImage;

    public User() {
    }

    public User(String funId) {
        this.funId = funId;
    }

    public User(String funId, String name, String phone, String headImage, String backImage) {
        this.funId = funId;
        this.name = name;
        this.phone = phone;
        this.headImage = headImage;
        this.backImage = backImage;
    }

    public String getFunId() {
        return tokay(funId);
    }

    public void setFunId(String funId) {
        this.funId = funId;
    }

    public String getName() {
        return tokay(name);
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return tokay(phone);
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getHeadImage() {
        return tokay(headImage);
    }

    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }

    public String getBackImage() {
        return tokay(backImage);
    }

    public void setBackImage(String backImage) {
        this.backImage = backImage;
    }

    public void setUser(User user){
        this.funId = user.funId;
        this.name = user.name;
        this.phone = user.phone;
        this.headImage = user.headImage;
        this.backImage = user.backImage;
    }

}
