package com.ytying.ytblog.model.domin;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.ytying.ytblog.model.DoObject;

/**
 * Entity mapped to table USER.
 */
public class User extends DoObject {

    private String funId;
    private String email;
    private String nickname;
    private String createTime;
    private Integer designer;
    private String sex;
    private String phoneNumber;
    private String qqNumber;
    private String motto;
    private String province;
    private String city;
    private String headImage;
    private String backImage;

    public User() {
    }

    public User(String funId) {
        this.funId = funId;
    }

    public User(String funId, String email, String nickname, String createTime, Integer designer, String sex, String phoneNumber, String qqNumber, String motto, String province, String city, String headImage, String backImage) {
        this.funId = funId;
        this.email = email;
        this.nickname = nickname;
        this.createTime = createTime;
        this.designer = designer;
        this.sex = sex;
        this.phoneNumber = phoneNumber;
        this.qqNumber = qqNumber;
        this.motto = motto;
        this.province = province;
        this.city = city;
        this.headImage = headImage;
        this.backImage = backImage;
    }

    public String getFunId() {
        return tokay(funId);
    }

    public void setFunId(String funId) {
        this.funId = funId;
    }

    public String getEmail() {
        return tokay(email);
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNickname() {
        return tokay(nickname);
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public Integer getDesigner() {
        return designer;
    }

    public void setDesigner(Integer designer) {
        this.designer = designer;
    }

    public String getSex() {
        return tokay(sex);
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getQqNumber() {
        return qqNumber;
    }

    public void setQqNumber(String qqNumber) {
        this.qqNumber = qqNumber;
    }

    public String getMotto() {
        return tokay(motto);
    }

    public void setMotto(String motto) {
        this.motto = motto;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getHeadImage() {
        return headImage;
    }

    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }

    public String getBackImage() {
        return backImage;
    }

    public void setBackImage(String backImage) {
        this.backImage = backImage;
    }

}
